### PR TITLE
fix: do not alter source path for install binary when untarring on macOS

### LINKED ISSUE #244: Install script fails on macOS
**Description of the bug**
When running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/deislabs/spiderlightning/main/install.sh)"` the final step fails with `install: ./release/slight: No such file or directory`

**To Reproduce**
Execute `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/deislabs/spiderlightning/main/install.sh)"` on macOS 13

**Additional context**
The `slight` file is created on the current working dir and not on `/usr/local/bin` as intended.

### PR DESCRIPTION
**Pull request by raymundovr**
This PR fixes #244 
Signed-off-by: Raymundo Vásquez Ruiz <raymundo.vr@protonmail.com>

### CODE REVIEW

**Comment by Mossaka** [comment]
Thanks for your contribution!

I remember we purposely did `strip-components=1` to differentiate Linux and MacOS in this PR https://github.com/deislabs/spiderlightning/pull/223. @danbugs FYI

**Comment by raymundovr** [comment]
@Mossaka I see, with that arg the install process is broken.
Why do you need that differentiation?

**Comment by danbugs** [comment]
@raymundovr ~ Thank you for your PR! I remember this is smt we specifically added because `tar`ring without the `strip-components` flag caused it to fail. I tried the current installation script on my Mac, and couldn't replicate your issue: 



To investigate, I tried the commands individually:

(1) **with `strip-components`**:
```sh
curl -L -s https://github.com/deislabs/spiderlightning/releases/download/v0.2.0/slight-macos-aarch64.tar.gz --output slight-macos-aarch64.tar.gz
tar -xf slight-macos-aarch64.tar.gz --strip-components=1
```

At this point, you should have a `slight` binary inside of a `release` folder in the working directory that you ran the command in. This is important because, later, the install script calls: `sudo install ./release/slight-macos-aarch64.tar.gz /usr/local/bin`.

(2) **without `strip-components`**
```sh
curl -L -s https://github.com/deislabs/spiderlightning/releases/download/v0.2.0/slight-macos-aarch64.tar.gz --output slight-macos-aarch64.tar.gz
tar -xf slight-macos-aarch64.tar.gz
```

At this point, without `strip-components`, I have a `slight binary inside of a `aarch64-apple-darwin/release` folder, which would cause the later command `sudo install ./release/slight-macos-aarch64.tar.gz /usr/local/bin` to fail.

Could you post the output of `uname`, and `uname -m` in your machine?

**Comment by raymundovr** [comment]
Hi @danbugs this is really odd :(
Here's the output of the requested commands
```
# r@Raymundos-MBP  in ~ [21:14:50] 🙃
; uname
Darwin

# r@Raymundos-MBP  in ~ [21:37:22] 🙃
; uname -m
x86_64
```

Not sure what's going on.

**Comment by danbugs** [comment]
> Hi @danbugs this is really odd :( Here's the output of the requested commands
> 
> ```
> # r@Raymundos-MBP  in ~ [21:14:50] 🙃
> ; uname
> Darwin
> 
> # r@Raymundos-MBP  in ~ [21:37:22] 🙃
> ; uname -m
> x86_64
> ```
> 
> Not sure what's going on.

@raymundovr ~ for me, I have:
```sh
➜  ~ uname && uname -m 
Darwin
arm64
```

I'm wondering if `tar` might work differently in `arm64` somehow... 

@Mossaka: You have an `x86_64` Mac, right? Could you try to replicate this?

@raymundovr: Could you just confirm the output of when you run:
```sh
mkdir spiderlightning_test && cd spiderlightning_test && curl -L -s https://github.com/deislabs/spiderlightning/releases/download/v0.2.0/slight-macos-aarch64.tar.gz --output slight-macos-aarch64.tar.gz && tar -xf slight-macos-aarch64.tar.gz --strip-components=1 && ls
```

After this, you can clean-up w/:
```sh
cd .. && rm -rf spiderlightning_test
```

**Comment by raymundovr** [comment]
@danbugs 
It's behaving totally different, the output of the commands that you sent is what you expect as correct behavior
```
# r@Raymundos-MBP  in ~ [21:37:25] 🙃
; mkdir spiderlightning_test && cd spiderlightning_test && curl -L -s https://github.com/deislabs/spiderlightning/releases/download/v0.2.0/slight-macos-aarch64.tar.gz --output slight-macos-aarch64.tar.gz && tar -xf slight-macos-aarch64.tar.gz --strip-components=1 && ls
release                     slight-macos-aarch64.tar.gz
```

The release folder is there 👆🏽

Contrary to what happens when running the install script
```
# r@Raymundos-MBP  in ~/slight_test [22:10:16] 🙃
; /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/deislabs/spiderlightning/main/install.sh)" && ls
>>> LATEST RELEASE: v0.2.0...
>>> DONLOADING FROM: https://github.com/deislabs/spiderlightning/releases/download/v0.2.0/slight-macos-amd64.tar.gz...
>>> DOWNLOADED BINARY TAR.
>>> EXTRACTED BINARY TAR.
install: ./release/slight: No such file or directory
>>> INSTALLED BINARY.
>>> CLEANED UP.
slight
```
Here the untar left a single file without release folder.

**Comment by danbugs** [comment]
I've figured it out!

When I run the same test command, but to get the binary for `x86_64` machines (i.e., `amd64`), we get the `slight` binary by itself:
```sh
mkdir spiderlightning_test && cd spiderlightning_test && curl -L -s https://github.com/deislabs/spiderlightning/releases/download/v0.2.0/slight-macos-amd64.tar.gz --output slight-macos-amd64.tar.gz && tar -xf slight-macos-amd64.tar.gz --strip-components=1 && ls
slight                    slight-macos-amd64.tar.gz
```

Could you modify this PR to `tar -xf` (i.e., not `strip-components`) only `x86_64` Macs?

cc: @Mossaka ~ You don't have to try and replicate this anymore!

**Comment by raymundovr** [comment]
@danbugs i've missed that!

How's the tarring being done?
Wouldn't be better to have a normalized tar?

**Comment by raymundovr** [comment]
@danbugs in any cases I have applied the change, in await for the decision to modify the tarring or not.

i've followed the same logic that is present lines above when deciding which file to download.

**Comment by danbugs** [comment]
> @danbugs i've missed that!
> 
> How's the tarring being done? Wouldn't be better to have a normalized tar?

Actually, the issue is happening _because_ the `tar`ring is normalized - we're always doing `tar -C target/ ..`.

However, when building for `arm64` (i.e., `cargo build --target aarch64-apple-darwin`), the binary is placed under `target/aarch64-apple-darwin/release/` as opposed to `target/release`, so, when we `tar` it, the `aarch64-apple-darwin` folder comes with it.

To fix that, we'd have to modify the release script here:
https://github.com/deislabs/spiderlightning/blob/086eac1192125e63196ba72b384513e127f0359d/.github/workflows/release.yml#L85

It should be: `tar -C target/aarch64-apple-darwin -czvf slight-macos-aarch64.tar.gz release/slight` instead.

This, however, won't fix the installation for the current release, so this PR is needed regardless, at least for now. We could undo this change and fix release script before `v0.3`, though.

**Review by danbugs — APPROVED** [review]
LGTM!

**Comment by raymundovr** [comment]
@danbugs  Got it, thanks for the explanation!

**Pull request merged**
